{
//=========Macro generated from canvas: csubdata/Average Charge - Pedestal subtracted
//=========  (Sun Mar 28 16:15:59 2010) by ROOT version5.26/00
   TCanvas *csubdata = new TCanvas("csubdata", "Average Charge - Pedestal subtracted",60,82,1000,1000);
   gStyle->SetOptFit(1);
   csubdata->Range(0,0,1,1);
   csubdata->SetBorderSize(2);
   csubdata->SetFrameFillColor(0);
  
// ------------>Primitives in pad: csubdata_1
   TPad *csubdata_1 = new TPad("csubdata_1", "csubdata_1",0.01,0.6766667,0.3233333,0.99);
   csubdata_1->Draw();
   csubdata_1->cd();
   csubdata_1->Range(-25.14699,-10.85968,24.98635,98.36832);
   csubdata_1->SetBorderSize(2);
   csubdata_1->SetFrameFillColor(0);
   
   TH1F *Data after pedestals subtraction channel 0__1 = new TH1F("Data after pedestals subtraction channel 0__1","Data after pedestals subtraction channel 0",100,-20,20);
   Data after pedestals subtraction channel 0__1->SetBinContent(29,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(31,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(32,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(33,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(34,6);
   Data after pedestals subtraction channel 0__1->SetBinContent(35,6);
   Data after pedestals subtraction channel 0__1->SetBinContent(36,7);
   Data after pedestals subtraction channel 0__1->SetBinContent(37,13);
   Data after pedestals subtraction channel 0__1->SetBinContent(38,13);
   Data after pedestals subtraction channel 0__1->SetBinContent(39,19);
   Data after pedestals subtraction channel 0__1->SetBinContent(40,26);
   Data after pedestals subtraction channel 0__1->SetBinContent(41,34);
   Data after pedestals subtraction channel 0__1->SetBinContent(42,43);
   Data after pedestals subtraction channel 0__1->SetBinContent(43,42);
   Data after pedestals subtraction channel 0__1->SetBinContent(44,49);
   Data after pedestals subtraction channel 0__1->SetBinContent(45,51);
   Data after pedestals subtraction channel 0__1->SetBinContent(46,56);
   Data after pedestals subtraction channel 0__1->SetBinContent(47,83);
   Data after pedestals subtraction channel 0__1->SetBinContent(48,61);
   Data after pedestals subtraction channel 0__1->SetBinContent(49,52);
   Data after pedestals subtraction channel 0__1->SetBinContent(50,66);
   Data after pedestals subtraction channel 0__1->SetBinContent(51,72);
   Data after pedestals subtraction channel 0__1->SetBinContent(52,61);
   Data after pedestals subtraction channel 0__1->SetBinContent(53,47);
   Data after pedestals subtraction channel 0__1->SetBinContent(54,34);
   Data after pedestals subtraction channel 0__1->SetBinContent(55,38);
   Data after pedestals subtraction channel 0__1->SetBinContent(56,24);
   Data after pedestals subtraction channel 0__1->SetBinContent(57,29);
   Data after pedestals subtraction channel 0__1->SetBinContent(58,21);
   Data after pedestals subtraction channel 0__1->SetBinContent(59,13);
   Data after pedestals subtraction channel 0__1->SetBinContent(60,12);
   Data after pedestals subtraction channel 0__1->SetBinContent(61,5);
   Data after pedestals subtraction channel 0__1->SetBinContent(62,6);
   Data after pedestals subtraction channel 0__1->SetBinContent(63,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(64,3);
   Data after pedestals subtraction channel 0__1->SetBinContent(65,3);
   Data after pedestals subtraction channel 0__1->SetBinContent(66,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(67,3);
   Data after pedestals subtraction channel 0__1->SetBinContent(68,3);
   Data after pedestals subtraction channel 0__1->SetBinContent(69,2);
   Data after pedestals subtraction channel 0__1->SetBinContent(70,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(71,6);
   Data after pedestals subtraction channel 0__1->SetBinContent(73,2);
   Data after pedestals subtraction channel 0__1->SetBinContent(74,2);
   Data after pedestals subtraction channel 0__1->SetBinContent(75,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(76,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(81,1);
   Data after pedestals subtraction channel 0__1->SetBinContent(83,1);
   Data after pedestals subtraction channel 0__1->SetEntries(1024);
   Data after pedestals subtraction channel 0__1->SetDirectory(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-20,20);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(4);
   gaus->SetLineWidth(3);
   gaus->SetChisquare(50.64025);
   gaus->SetNDF(45);
   gaus->SetParameter(0,65.7449);
   gaus->SetParError(0,2.586007);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,-0.8748498);
   gaus->SetParError(1,0.07618151);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,2.364859);
   gaus->SetParError(2,0.05443996);
   gaus->SetParLimits(2,0,27.48752);
   Data after pedestals subtraction channel 0__1->GetListOfFunctions()->Add(gaus);
   
   TPaveStats *ptstats = new TPaveStats(0.6185593,0.5197006,0.9774417,0.9268453,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(2);
   ptstats->SetFillColor(19);
   ptstats->SetTextAlign(12);
   TText *text = ptstats->AddText("Data after pedestals subtraction channel 0");
   text->SetTextSize(0.05351045);
   text = ptstats->AddText("Entries = 1024   ");
   text = ptstats->AddText("#chi^{2} / ndf = 50.64 / 45");
   text = ptstats->AddText("Prob  = 0.2608");
   text = ptstats->AddText("Constant = 65.74 #pm 2.59 ");
   text = ptstats->AddText("Mean     = -0.8748 #pm 0.0762 ");
   text = ptstats->AddText("Sigma    = 2.365 #pm 0.054 ");
   ptstats->SetOptStat(11);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   Data after pedestals subtraction channel 0__1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Data after pedestals subtraction channel 0__1->GetListOfFunctions());
   Data after pedestals subtraction channel 0__1->GetXaxis()->SetTitle("ADC Counts");
   Data after pedestals subtraction channel 0__1->Draw("");
   
   TPaveText *pt = new TPaveText(0.01,0.9398385,0.71,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(19);
   text = pt->AddText("Data after pedestals subtraction channel 0");
   pt->Draw();
   csubdata_1->Modified();
   csubdata->cd();
  
// ------------>Primitives in pad: csubdata_2
   csubdata_2 = new TPad("csubdata_2", "csubdata_2",0.3433333,0.6766667,0.6566667,0.99);
   csubdata_2->Draw();
   csubdata_2->cd();
   csubdata_2->Range(-25,-10.36875,25,93.31875);
   csubdata_2->SetBorderSize(2);
   csubdata_2->SetFrameFillColor(0);
   
   TH1F *Data after pedestals subtraction channel 1__2 = new TH1F("Data after pedestals subtraction channel 1__2","Data after pedestals subtraction channel 1",100,-20,20);
   Data after pedestals subtraction channel 1__2->SetBinContent(29,1);
   Data after pedestals subtraction channel 1__2->SetBinContent(32,1);
   Data after pedestals subtraction channel 1__2->SetBinContent(33,2);
   Data after pedestals subtraction channel 1__2->SetBinContent(34,1);
   Data after pedestals subtraction channel 1__2->SetBinContent(35,5);
   Data after pedestals subtraction channel 1__2->SetBinContent(36,2);
   Data after pedestals subtraction channel 1__2->SetBinContent(37,5);
   Data after pedestals subtraction channel 1__2->SetBinContent(38,9);
   Data after pedestals subtraction channel 1__2->SetBinContent(39,16);
   Data after pedestals subtraction channel 1__2->SetBinContent(40,18);
   Data after pedestals subtraction channel 1__2->SetBinContent(41,29);
   Data after pedestals subtraction channel 1__2->SetBinContent(42,33);
   Data after pedestals subtraction channel 1__2->SetBinContent(43,33);
   Data after pedestals subtraction channel 1__2->SetBinContent(44,53);
   Data after pedestals subtraction channel 1__2->SetBinContent(45,46);
   Data after pedestals subtraction channel 1__2->SetBinContent(46,59);
   Data after pedestals subtraction channel 1__2->SetBinContent(47,68);
   Data after pedestals subtraction channel 1__2->SetBinContent(48,52);
   Data after pedestals subtraction channel 1__2->SetBinContent(49,79);
   Data after pedestals subtraction channel 1__2->SetBinContent(50,63);
   Data after pedestals subtraction channel 1__2->SetBinContent(51,65);
   Data after pedestals subtraction channel 1__2->SetBinContent(52,50);
   Data after pedestals subtraction channel 1__2->SetBinContent(53,60);
   Data after pedestals subtraction channel 1__2->SetBinContent(54,54);
   Data after pedestals subtraction channel 1__2->SetBinContent(55,42);
   Data after pedestals subtraction channel 1__2->SetBinContent(56,27);
   Data after pedestals subtraction channel 1__2->SetBinContent(57,39);
   Data after pedestals subtraction channel 1__2->SetBinContent(58,30);
   Data after pedestals subtraction channel 1__2->SetBinContent(59,13);
   Data after pedestals subtraction channel 1__2->SetBinContent(60,14);
   Data after pedestals subtraction channel 1__2->SetBinContent(61,7);
   Data after pedestals subtraction channel 1__2->SetBinContent(62,8);
   Data after pedestals subtraction channel 1__2->SetBinContent(63,4);
   Data after pedestals subtraction channel 1__2->SetBinContent(64,6);
   Data after pedestals subtraction channel 1__2->SetBinContent(65,4);
   Data after pedestals subtraction channel 1__2->SetBinContent(66,6);
   Data after pedestals subtraction channel 1__2->SetBinContent(67,2);
   Data after pedestals subtraction channel 1__2->SetBinContent(69,2);
   Data after pedestals subtraction channel 1__2->SetBinContent(70,2);
   Data after pedestals subtraction channel 1__2->SetBinContent(71,4);
   Data after pedestals subtraction channel 1__2->SetBinContent(72,1);
   Data after pedestals subtraction channel 1__2->SetBinContent(73,1);
   Data after pedestals subtraction channel 1__2->SetBinContent(74,2);
   Data after pedestals subtraction channel 1__2->SetBinContent(75,1);
   Data after pedestals subtraction channel 1__2->SetBinContent(76,1);
   Data after pedestals subtraction channel 1__2->SetBinContent(78,1);
   Data after pedestals subtraction channel 1__2->SetBinContent(80,2);
   Data after pedestals subtraction channel 1__2->SetBinContent(87,1);
   Data after pedestals subtraction channel 1__2->SetEntries(1024);
   Data after pedestals subtraction channel 1__2->SetDirectory(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-20,20);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(4);
   gaus->SetLineWidth(3);
   gaus->SetChisquare(54.55617);
   gaus->SetNDF(45);
   gaus->SetParameter(0,66.177);
   gaus->SetParError(0,2.673893);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,-0.3960629);
   gaus->SetParError(1,0.07698707);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,2.34084);
   gaus->SetParError(2,0.05811729);
   gaus->SetParLimits(2,0,27.24793);
   Data after pedestals subtraction channel 1__2->GetListOfFunctions()->Add(gaus);
   
   ptstats = new TPaveStats(0.6185593,0.5295508,0.9774417,0.9202784,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(2);
   ptstats->SetFillColor(19);
   ptstats->SetTextAlign(12);
   text = ptstats->AddText("Data after pedestals subtraction channel 1");
   text->SetTextSize(0.05135277);
   text = ptstats->AddText("Entries = 1024   ");
   text = ptstats->AddText("#chi^{2} / ndf = 54.56 / 45");
   text = ptstats->AddText("Prob  = 0.1556");
   text = ptstats->AddText("Constant = 66.18 #pm 2.67 ");
   text = ptstats->AddText("Mean     = -0.3961 #pm 0.0770 ");
   text = ptstats->AddText("Sigma    = 2.341 #pm 0.058 ");
   ptstats->SetOptStat(11);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   Data after pedestals subtraction channel 1__2->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Data after pedestals subtraction channel 1__2->GetListOfFunctions());
   Data after pedestals subtraction channel 1__2->GetXaxis()->SetTitle("ADC Counts");
   Data after pedestals subtraction channel 1__2->Draw("");
   
   pt = new TPaveText(0.01,0.9398385,0.71,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(19);
   text = pt->AddText("Data after pedestals subtraction channel 1");
   pt->Draw();
   csubdata_2->Modified();
   csubdata->cd();
  
// ------------>Primitives in pad: csubdata_3
   csubdata_3 = new TPad("csubdata_3", "csubdata_3",0.6766667,0.6766667,0.99,0.99);
   csubdata_3->Draw();
   csubdata_3->cd();
   csubdata_3->Range(-25,-11.41875,25,102.7688);
   csubdata_3->SetBorderSize(2);
   csubdata_3->SetFrameFillColor(0);
   
   TH1F *Data after pedestals subtraction channel 2__3 = new TH1F("Data after pedestals subtraction channel 2__3","Data after pedestals subtraction channel 2",100,-20,20);
   Data after pedestals subtraction channel 2__3->SetBinContent(0,3);
   Data after pedestals subtraction channel 2__3->SetBinContent(6,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(8,2);
   Data after pedestals subtraction channel 2__3->SetBinContent(12,3);
   Data after pedestals subtraction channel 2__3->SetBinContent(13,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(15,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(19,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(23,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(26,3);
   Data after pedestals subtraction channel 2__3->SetBinContent(27,2);
   Data after pedestals subtraction channel 2__3->SetBinContent(28,2);
   Data after pedestals subtraction channel 2__3->SetBinContent(30,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(31,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(32,2);
   Data after pedestals subtraction channel 2__3->SetBinContent(33,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(34,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(36,3);
   Data after pedestals subtraction channel 2__3->SetBinContent(37,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(38,2);
   Data after pedestals subtraction channel 2__3->SetBinContent(39,4);
   Data after pedestals subtraction channel 2__3->SetBinContent(40,12);
   Data after pedestals subtraction channel 2__3->SetBinContent(41,17);
   Data after pedestals subtraction channel 2__3->SetBinContent(42,22);
   Data after pedestals subtraction channel 2__3->SetBinContent(43,20);
   Data after pedestals subtraction channel 2__3->SetBinContent(44,32);
   Data after pedestals subtraction channel 2__3->SetBinContent(45,41);
   Data after pedestals subtraction channel 2__3->SetBinContent(46,60);
   Data after pedestals subtraction channel 2__3->SetBinContent(47,56);
   Data after pedestals subtraction channel 2__3->SetBinContent(48,70);
   Data after pedestals subtraction channel 2__3->SetBinContent(49,81);
   Data after pedestals subtraction channel 2__3->SetBinContent(50,87);
   Data after pedestals subtraction channel 2__3->SetBinContent(51,74);
   Data after pedestals subtraction channel 2__3->SetBinContent(52,63);
   Data after pedestals subtraction channel 2__3->SetBinContent(53,80);
   Data after pedestals subtraction channel 2__3->SetBinContent(54,63);
   Data after pedestals subtraction channel 2__3->SetBinContent(55,43);
   Data after pedestals subtraction channel 2__3->SetBinContent(56,43);
   Data after pedestals subtraction channel 2__3->SetBinContent(57,30);
   Data after pedestals subtraction channel 2__3->SetBinContent(58,26);
   Data after pedestals subtraction channel 2__3->SetBinContent(59,12);
   Data after pedestals subtraction channel 2__3->SetBinContent(60,13);
   Data after pedestals subtraction channel 2__3->SetBinContent(61,14);
   Data after pedestals subtraction channel 2__3->SetBinContent(62,4);
   Data after pedestals subtraction channel 2__3->SetBinContent(63,5);
   Data after pedestals subtraction channel 2__3->SetBinContent(64,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(65,3);
   Data after pedestals subtraction channel 2__3->SetBinContent(66,4);
   Data after pedestals subtraction channel 2__3->SetBinContent(67,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(68,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(69,4);
   Data after pedestals subtraction channel 2__3->SetBinContent(70,2);
   Data after pedestals subtraction channel 2__3->SetBinContent(72,2);
   Data after pedestals subtraction channel 2__3->SetBinContent(73,1);
   Data after pedestals subtraction channel 2__3->SetBinContent(79,1);
   Data after pedestals subtraction channel 2__3->SetEntries(1024);
   Data after pedestals subtraction channel 2__3->SetDirectory(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-20,20);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(4);
   gaus->SetLineWidth(3);
   gaus->SetChisquare(60.53865);
   gaus->SetNDF(50);
   gaus->SetParameter(0,77.85984);
   gaus->SetParError(0,3.162373);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,-0.03854797);
   gaus->SetParError(1,0.06390191);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,1.969742);
   gaus->SetParError(2,0.04884211);
   gaus->SetParLimits(2,0,28.14988);
   Data after pedestals subtraction channel 2__3->GetListOfFunctions()->Add(gaus);
   
   ptstats = new TPaveStats(0.6185593,0.5426845,0.9774417,0.9235619,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(2);
   ptstats->SetFillColor(19);
   ptstats->SetTextAlign(12);
   text = ptstats->AddText("Data after pedestals subtraction channel 2");
   text->SetTextSize(0.05005816);
   text = ptstats->AddText("Entries = 1024   ");
   text = ptstats->AddText("#chi^{2} / ndf = 60.54 / 50");
   text = ptstats->AddText("Prob  = 0.1461");
   text = ptstats->AddText("Constant = 77.86 #pm 3.16 ");
   text = ptstats->AddText("Mean     = -0.03855 #pm 0.06390 ");
   text = ptstats->AddText("Sigma    =  1.97 #pm 0.05 ");
   ptstats->SetOptStat(11);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   Data after pedestals subtraction channel 2__3->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Data after pedestals subtraction channel 2__3->GetListOfFunctions());
   Data after pedestals subtraction channel 2__3->GetXaxis()->SetTitle("ADC Counts");
   Data after pedestals subtraction channel 2__3->Draw("");
   
   pt = new TPaveText(0.01,0.9398385,0.71,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(19);
   text = pt->AddText("Data after pedestals subtraction channel 2");
   pt->Draw();
   csubdata_3->Modified();
   csubdata->cd();
  
// ------------>Primitives in pad: csubdata_4
   csubdata_4 = new TPad("csubdata_4", "csubdata_4",0.01004016,0.3436214,0.3242972,0.6574074);
   csubdata_4->Draw();
   csubdata_4->cd();
   csubdata_4->Range(-25,-12.73125,25,114.5813);
   csubdata_4->SetBorderSize(2);
   csubdata_4->SetFrameFillColor(0);
   
   TH1F *Data after pedestals subtraction channel 3__4 = new TH1F("Data after pedestals subtraction channel 3__4","Data after pedestals subtraction channel 3",100,-20,20);
   Data after pedestals subtraction channel 3__4->SetBinContent(0,5);
   Data after pedestals subtraction channel 3__4->SetBinContent(2,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(3,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(9,2);
   Data after pedestals subtraction channel 3__4->SetBinContent(12,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(13,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(16,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(18,3);
   Data after pedestals subtraction channel 3__4->SetBinContent(20,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(23,2);
   Data after pedestals subtraction channel 3__4->SetBinContent(24,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(25,2);
   Data after pedestals subtraction channel 3__4->SetBinContent(31,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(32,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(33,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(35,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(36,2);
   Data after pedestals subtraction channel 3__4->SetBinContent(37,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(38,3);
   Data after pedestals subtraction channel 3__4->SetBinContent(39,4);
   Data after pedestals subtraction channel 3__4->SetBinContent(40,6);
   Data after pedestals subtraction channel 3__4->SetBinContent(41,7);
   Data after pedestals subtraction channel 3__4->SetBinContent(42,14);
   Data after pedestals subtraction channel 3__4->SetBinContent(43,19);
   Data after pedestals subtraction channel 3__4->SetBinContent(44,24);
   Data after pedestals subtraction channel 3__4->SetBinContent(45,36);
   Data after pedestals subtraction channel 3__4->SetBinContent(46,51);
   Data after pedestals subtraction channel 3__4->SetBinContent(47,54);
   Data after pedestals subtraction channel 3__4->SetBinContent(48,73);
   Data after pedestals subtraction channel 3__4->SetBinContent(49,68);
   Data after pedestals subtraction channel 3__4->SetBinContent(50,95);
   Data after pedestals subtraction channel 3__4->SetBinContent(51,97);
   Data after pedestals subtraction channel 3__4->SetBinContent(52,65);
   Data after pedestals subtraction channel 3__4->SetBinContent(53,74);
   Data after pedestals subtraction channel 3__4->SetBinContent(54,64);
   Data after pedestals subtraction channel 3__4->SetBinContent(55,61);
   Data after pedestals subtraction channel 3__4->SetBinContent(56,49);
   Data after pedestals subtraction channel 3__4->SetBinContent(57,30);
   Data after pedestals subtraction channel 3__4->SetBinContent(58,31);
   Data after pedestals subtraction channel 3__4->SetBinContent(59,17);
   Data after pedestals subtraction channel 3__4->SetBinContent(60,14);
   Data after pedestals subtraction channel 3__4->SetBinContent(61,8);
   Data after pedestals subtraction channel 3__4->SetBinContent(62,6);
   Data after pedestals subtraction channel 3__4->SetBinContent(63,4);
   Data after pedestals subtraction channel 3__4->SetBinContent(64,2);
   Data after pedestals subtraction channel 3__4->SetBinContent(65,3);
   Data after pedestals subtraction channel 3__4->SetBinContent(66,3);
   Data after pedestals subtraction channel 3__4->SetBinContent(67,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(69,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(71,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(73,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(75,3);
   Data after pedestals subtraction channel 3__4->SetBinContent(76,2);
   Data after pedestals subtraction channel 3__4->SetBinContent(77,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(78,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(79,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(80,1);
   Data after pedestals subtraction channel 3__4->SetBinContent(83,1);
   Data after pedestals subtraction channel 3__4->SetEntries(1024);
   Data after pedestals subtraction channel 3__4->SetDirectory(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-20,20);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(4);
   gaus->SetLineWidth(3);
   gaus->SetChisquare(51.5207);
   gaus->SetNDF(54);
   gaus->SetParameter(0,80.88555);
   gaus->SetParError(0,3.337364);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,0.1913973);
   gaus->SetParError(1,0.06158381);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,1.90936);
   gaus->SetParError(2,0.04956874);
   gaus->SetParLimits(2,0,28.80996);
   Data after pedestals subtraction channel 3__4->GetListOfFunctions()->Add(gaus);
   
   ptstats = new TPaveStats(0.6166134,0.5901639,0.9744409,0.9180328,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(2);
   ptstats->SetFillColor(19);
   ptstats->SetTextAlign(12);
   text = ptstats->AddText("Data after pedestals subtraction channel 3");
   text->SetTextSize(0.04309133);
   text = ptstats->AddText("Entries = 1024   ");
   text = ptstats->AddText("#chi^{2} / ndf = 51.52 / 54");
   text = ptstats->AddText("Prob  = 0.5706");
   text = ptstats->AddText("Constant = 80.89 #pm 3.34 ");
   text = ptstats->AddText("Mean     = 0.1914 #pm 0.0616 ");
   text = ptstats->AddText("Sigma    = 1.909 #pm 0.050 ");
   ptstats->SetOptStat(11);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   Data after pedestals subtraction channel 3__4->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Data after pedestals subtraction channel 3__4->GetListOfFunctions());
   Data after pedestals subtraction channel 3__4->GetXaxis()->SetTitle("ADC Counts");
   Data after pedestals subtraction channel 3__4->Draw("");
   
   pt = new TPaveText(0.01,0.9398385,0.71,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(19);
   text = pt->AddText("Data after pedestals subtraction channel 3");
   pt->Draw();
   csubdata_4->Modified();
   csubdata->cd();
  
// ------------>Primitives in pad: csubdata_5
   csubdata_5 = new TPad("csubdata_5", "csubdata_5",0.3433333,0.3433333,0.6566667,0.6566667);
   csubdata_5->Draw();
   csubdata_5->cd();
   csubdata_5->Range(-25,-12.20625,25,109.8563);
   csubdata_5->SetBorderSize(2);
   csubdata_5->SetFrameFillColor(0);
   
   TH1F *Data after pedestals subtraction channel 4__5 = new TH1F("Data after pedestals subtraction channel 4__5","Data after pedestals subtraction channel 4",100,-20,20);
   Data after pedestals subtraction channel 4__5->SetBinContent(0,3);
   Data after pedestals subtraction channel 4__5->SetBinContent(2,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(11,2);
   Data after pedestals subtraction channel 4__5->SetBinContent(16,2);
   Data after pedestals subtraction channel 4__5->SetBinContent(17,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(18,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(19,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(21,2);
   Data after pedestals subtraction channel 4__5->SetBinContent(26,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(30,3);
   Data after pedestals subtraction channel 4__5->SetBinContent(31,2);
   Data after pedestals subtraction channel 4__5->SetBinContent(33,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(34,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(35,2);
   Data after pedestals subtraction channel 4__5->SetBinContent(36,3);
   Data after pedestals subtraction channel 4__5->SetBinContent(37,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(38,4);
   Data after pedestals subtraction channel 4__5->SetBinContent(39,10);
   Data after pedestals subtraction channel 4__5->SetBinContent(40,3);
   Data after pedestals subtraction channel 4__5->SetBinContent(41,7);
   Data after pedestals subtraction channel 4__5->SetBinContent(42,16);
   Data after pedestals subtraction channel 4__5->SetBinContent(43,17);
   Data after pedestals subtraction channel 4__5->SetBinContent(44,30);
   Data after pedestals subtraction channel 4__5->SetBinContent(45,32);
   Data after pedestals subtraction channel 4__5->SetBinContent(46,50);
   Data after pedestals subtraction channel 4__5->SetBinContent(47,29);
   Data after pedestals subtraction channel 4__5->SetBinContent(48,64);
   Data after pedestals subtraction channel 4__5->SetBinContent(49,72);
   Data after pedestals subtraction channel 4__5->SetBinContent(50,76);
   Data after pedestals subtraction channel 4__5->SetBinContent(51,74);
   Data after pedestals subtraction channel 4__5->SetBinContent(52,74);
   Data after pedestals subtraction channel 4__5->SetBinContent(53,93);
   Data after pedestals subtraction channel 4__5->SetBinContent(54,66);
   Data after pedestals subtraction channel 4__5->SetBinContent(55,65);
   Data after pedestals subtraction channel 4__5->SetBinContent(56,50);
   Data after pedestals subtraction channel 4__5->SetBinContent(57,45);
   Data after pedestals subtraction channel 4__5->SetBinContent(58,29);
   Data after pedestals subtraction channel 4__5->SetBinContent(59,23);
   Data after pedestals subtraction channel 4__5->SetBinContent(60,18);
   Data after pedestals subtraction channel 4__5->SetBinContent(61,15);
   Data after pedestals subtraction channel 4__5->SetBinContent(62,4);
   Data after pedestals subtraction channel 4__5->SetBinContent(63,6);
   Data after pedestals subtraction channel 4__5->SetBinContent(64,5);
   Data after pedestals subtraction channel 4__5->SetBinContent(65,2);
   Data after pedestals subtraction channel 4__5->SetBinContent(66,3);
   Data after pedestals subtraction channel 4__5->SetBinContent(68,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(70,2);
   Data after pedestals subtraction channel 4__5->SetBinContent(71,4);
   Data after pedestals subtraction channel 4__5->SetBinContent(72,2);
   Data after pedestals subtraction channel 4__5->SetBinContent(73,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(75,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(76,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(77,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(78,1);
   Data after pedestals subtraction channel 4__5->SetBinContent(101,1);
   Data after pedestals subtraction channel 4__5->SetEntries(1024);
   Data after pedestals subtraction channel 4__5->SetDirectory(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-20,20);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(4);
   gaus->SetLineWidth(3);
   gaus->SetChisquare(74.46262);
   gaus->SetNDF(50);
   gaus->SetParameter(0,76.20733);
   gaus->SetParError(0,3.202294);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,0.4188217);
   gaus->SetParError(1,0.06508344);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,1.981572);
   gaus->SetParError(2,0.05311563);
   gaus->SetParLimits(2,0,27.81631);
   Data after pedestals subtraction channel 4__5->GetListOfFunctions()->Add(gaus);
   
   ptstats = new TPaveStats(0.62,0.675,0.98,0.995,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(2);
   ptstats->SetFillColor(19);
   ptstats->SetTextAlign(12);
   text = ptstats->AddText("Data after pedestals subtraction channel 4");
   text->SetTextSize(0.04205714);
   text = ptstats->AddText("Entries = 1024   ");
   text = ptstats->AddText("#chi^{2} / ndf = 74.46 / 50");
   text = ptstats->AddText("Prob  = 0.014");
   text = ptstats->AddText("Constant = 76.21 #pm 3.20 ");
   text = ptstats->AddText("Mean     = 0.4188 #pm 0.0651 ");
   text = ptstats->AddText("Sigma    = 1.982 #pm 0.053 ");
   ptstats->SetOptStat(11);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   Data after pedestals subtraction channel 4__5->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Data after pedestals subtraction channel 4__5->GetListOfFunctions());
   Data after pedestals subtraction channel 4__5->GetXaxis()->SetTitle("ADC Counts");
   Data after pedestals subtraction channel 4__5->Draw("");
   
   pt = new TPaveText(0.01,0.9398385,0.71,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(19);
   text = pt->AddText("Data after pedestals subtraction channel 4");
   pt->Draw();
   csubdata_5->Modified();
   csubdata->cd();
  
// ------------>Primitives in pad: csubdata_6
   csubdata_6 = new TPad("csubdata_6", "csubdata_6",0.6766667,0.3433333,0.99,0.6566667);
   csubdata_6->Draw();
   csubdata_6->cd();
   csubdata_6->Range(-25,-10.10625,25,90.95625);
   csubdata_6->SetBorderSize(2);
   csubdata_6->SetFrameFillColor(0);
   
   TH1F *Data after pedestals subtraction channel 5__6 = new TH1F("Data after pedestals subtraction channel 5__6","Data after pedestals subtraction channel 5",100,-20,20);
   Data after pedestals subtraction channel 5__6->SetBinContent(31,1);
   Data after pedestals subtraction channel 5__6->SetBinContent(33,2);
   Data after pedestals subtraction channel 5__6->SetBinContent(34,3);
   Data after pedestals subtraction channel 5__6->SetBinContent(35,9);
   Data after pedestals subtraction channel 5__6->SetBinContent(36,8);
   Data after pedestals subtraction channel 5__6->SetBinContent(37,8);
   Data after pedestals subtraction channel 5__6->SetBinContent(38,15);
   Data after pedestals subtraction channel 5__6->SetBinContent(39,19);
   Data after pedestals subtraction channel 5__6->SetBinContent(40,25);
   Data after pedestals subtraction channel 5__6->SetBinContent(41,24);
   Data after pedestals subtraction channel 5__6->SetBinContent(42,31);
   Data after pedestals subtraction channel 5__6->SetBinContent(43,40);
   Data after pedestals subtraction channel 5__6->SetBinContent(44,55);
   Data after pedestals subtraction channel 5__6->SetBinContent(45,73);
   Data after pedestals subtraction channel 5__6->SetBinContent(46,46);
   Data after pedestals subtraction channel 5__6->SetBinContent(47,59);
   Data after pedestals subtraction channel 5__6->SetBinContent(48,56);
   Data after pedestals subtraction channel 5__6->SetBinContent(49,65);
   Data after pedestals subtraction channel 5__6->SetBinContent(50,77);
   Data after pedestals subtraction channel 5__6->SetBinContent(51,50);
   Data after pedestals subtraction channel 5__6->SetBinContent(52,69);
   Data after pedestals subtraction channel 5__6->SetBinContent(53,46);
   Data after pedestals subtraction channel 5__6->SetBinContent(54,45);
   Data after pedestals subtraction channel 5__6->SetBinContent(55,31);
   Data after pedestals subtraction channel 5__6->SetBinContent(56,28);
   Data after pedestals subtraction channel 5__6->SetBinContent(57,26);
   Data after pedestals subtraction channel 5__6->SetBinContent(58,27);
   Data after pedestals subtraction channel 5__6->SetBinContent(59,17);
   Data after pedestals subtraction channel 5__6->SetBinContent(60,15);
   Data after pedestals subtraction channel 5__6->SetBinContent(61,7);
   Data after pedestals subtraction channel 5__6->SetBinContent(62,8);
   Data after pedestals subtraction channel 5__6->SetBinContent(63,2);
   Data after pedestals subtraction channel 5__6->SetBinContent(64,4);
   Data after pedestals subtraction channel 5__6->SetBinContent(65,5);
   Data after pedestals subtraction channel 5__6->SetBinContent(66,6);
   Data after pedestals subtraction channel 5__6->SetBinContent(67,1);
   Data after pedestals subtraction channel 5__6->SetBinContent(68,2);
   Data after pedestals subtraction channel 5__6->SetBinContent(69,1);
   Data after pedestals subtraction channel 5__6->SetBinContent(70,5);
   Data after pedestals subtraction channel 5__6->SetBinContent(71,1);
   Data after pedestals subtraction channel 5__6->SetBinContent(72,4);
   Data after pedestals subtraction channel 5__6->SetBinContent(73,2);
   Data after pedestals subtraction channel 5__6->SetBinContent(74,2);
   Data after pedestals subtraction channel 5__6->SetBinContent(76,2);
   Data after pedestals subtraction channel 5__6->SetBinContent(77,2);
   Data after pedestals subtraction channel 5__6->SetEntries(1024);
   Data after pedestals subtraction channel 5__6->SetDirectory(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-20,20);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(4);
   gaus->SetLineWidth(3);
   gaus->SetChisquare(55.07107);
   gaus->SetNDF(42);
   gaus->SetParameter(0,62.40872);
   gaus->SetParError(0,2.546691);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,-0.6897734);
   gaus->SetParError(1,0.08094087);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,2.485744);
   gaus->SetParError(2,0.06419419);
   gaus->SetParLimits(2,0,27.97046);
   Data after pedestals subtraction channel 5__6->GetListOfFunctions()->Add(gaus);
   
   ptstats = new TPaveStats(0.62,0.675,0.98,0.995,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(2);
   ptstats->SetFillColor(19);
   ptstats->SetTextAlign(12);
   text = ptstats->AddText("Data after pedestals subtraction channel 5");
   text->SetTextSize(0.04205714);
   text = ptstats->AddText("Entries = 1024   ");
   text = ptstats->AddText("#chi^{2} / ndf = 55.07 / 42");
   text = ptstats->AddText("Prob  = 0.08511");
   text = ptstats->AddText("Constant = 62.41 #pm 2.55 ");
   text = ptstats->AddText("Mean     = -0.6898 #pm 0.0809 ");
   text = ptstats->AddText("Sigma    = 2.486 #pm 0.064 ");
   ptstats->SetOptStat(11);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   Data after pedestals subtraction channel 5__6->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Data after pedestals subtraction channel 5__6->GetListOfFunctions());
   Data after pedestals subtraction channel 5__6->GetXaxis()->SetTitle("ADC Counts");
   Data after pedestals subtraction channel 5__6->Draw("");
   
   pt = new TPaveText(0.01,0.9398385,0.71,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(19);
   text = pt->AddText("Data after pedestals subtraction channel 5");
   pt->Draw();
   csubdata_6->Modified();
   csubdata->cd();
  
// ------------>Primitives in pad: csubdata_7
   csubdata_7 = new TPad("csubdata_7", "csubdata_7",0.01,0.01,0.3233333,0.3233333);
   csubdata_7->Draw();
   csubdata_7->cd();
   csubdata_7->Range(-25,-12.20625,25,109.8563);
   csubdata_7->SetBorderSize(2);
   csubdata_7->SetFrameFillColor(0);
   
   TH1F *Data after pedestals subtraction channel 6__7 = new TH1F("Data after pedestals subtraction channel 6__7","Data after pedestals subtraction channel 6",100,-20,20);
   Data after pedestals subtraction channel 6__7->SetBinContent(0,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(3,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(6,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(7,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(11,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(14,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(16,2);
   Data after pedestals subtraction channel 6__7->SetBinContent(18,3);
   Data after pedestals subtraction channel 6__7->SetBinContent(22,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(24,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(29,5);
   Data after pedestals subtraction channel 6__7->SetBinContent(31,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(38,4);
   Data after pedestals subtraction channel 6__7->SetBinContent(39,8);
   Data after pedestals subtraction channel 6__7->SetBinContent(40,12);
   Data after pedestals subtraction channel 6__7->SetBinContent(41,11);
   Data after pedestals subtraction channel 6__7->SetBinContent(42,11);
   Data after pedestals subtraction channel 6__7->SetBinContent(43,21);
   Data after pedestals subtraction channel 6__7->SetBinContent(44,27);
   Data after pedestals subtraction channel 6__7->SetBinContent(45,36);
   Data after pedestals subtraction channel 6__7->SetBinContent(46,58);
   Data after pedestals subtraction channel 6__7->SetBinContent(47,74);
   Data after pedestals subtraction channel 6__7->SetBinContent(48,78);
   Data after pedestals subtraction channel 6__7->SetBinContent(49,81);
   Data after pedestals subtraction channel 6__7->SetBinContent(50,75);
   Data after pedestals subtraction channel 6__7->SetBinContent(51,93);
   Data after pedestals subtraction channel 6__7->SetBinContent(52,80);
   Data after pedestals subtraction channel 6__7->SetBinContent(53,87);
   Data after pedestals subtraction channel 6__7->SetBinContent(54,65);
   Data after pedestals subtraction channel 6__7->SetBinContent(55,41);
   Data after pedestals subtraction channel 6__7->SetBinContent(56,40);
   Data after pedestals subtraction channel 6__7->SetBinContent(57,23);
   Data after pedestals subtraction channel 6__7->SetBinContent(58,18);
   Data after pedestals subtraction channel 6__7->SetBinContent(59,18);
   Data after pedestals subtraction channel 6__7->SetBinContent(60,11);
   Data after pedestals subtraction channel 6__7->SetBinContent(61,8);
   Data after pedestals subtraction channel 6__7->SetBinContent(62,2);
   Data after pedestals subtraction channel 6__7->SetBinContent(63,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(64,3);
   Data after pedestals subtraction channel 6__7->SetBinContent(65,2);
   Data after pedestals subtraction channel 6__7->SetBinContent(66,2);
   Data after pedestals subtraction channel 6__7->SetBinContent(67,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(68,2);
   Data after pedestals subtraction channel 6__7->SetBinContent(70,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(72,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(73,2);
   Data after pedestals subtraction channel 6__7->SetBinContent(75,4);
   Data after pedestals subtraction channel 6__7->SetBinContent(76,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(78,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(96,1);
   Data after pedestals subtraction channel 6__7->SetBinContent(101,1);
   Data after pedestals subtraction channel 6__7->SetEntries(1024);
   Data after pedestals subtraction channel 6__7->SetDirectory(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-20,20);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(4);
   gaus->SetLineWidth(3);
   gaus->SetChisquare(60.13203);
   gaus->SetNDF(46);
   gaus->SetParameter(0,85.17621);
   gaus->SetParError(0,3.574442);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,-0.05842563);
   gaus->SetParError(1,0.05902126);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,1.805983);
   gaus->SetParError(2,0.04950001);
   gaus->SetParLimits(2,0,27.66304);
   Data after pedestals subtraction channel 6__7->GetListOfFunctions()->Add(gaus);
   
   ptstats = new TPaveStats(0.62,0.675,0.98,0.995,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(2);
   ptstats->SetFillColor(19);
   ptstats->SetTextAlign(12);
   text = ptstats->AddText("Data after pedestals subtraction channel 6");
   text->SetTextSize(0.04205714);
   text = ptstats->AddText("Entries = 1024   ");
   text = ptstats->AddText("#chi^{2} / ndf = 60.13 / 46");
   text = ptstats->AddText("Prob  = 0.07886");
   text = ptstats->AddText("Constant = 85.18 #pm 3.57 ");
   text = ptstats->AddText("Mean     = -0.05843 #pm 0.05902 ");
   text = ptstats->AddText("Sigma    = 1.806 #pm 0.050 ");
   ptstats->SetOptStat(11);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   Data after pedestals subtraction channel 6__7->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Data after pedestals subtraction channel 6__7->GetListOfFunctions());
   Data after pedestals subtraction channel 6__7->GetXaxis()->SetTitle("ADC Counts");
   Data after pedestals subtraction channel 6__7->Draw("");
   
   pt = new TPaveText(0.01,0.9398385,0.71,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(19);
   text = pt->AddText("Data after pedestals subtraction channel 6");
   pt->Draw();
   csubdata_7->Modified();
   csubdata->cd();
  
// ------------>Primitives in pad: csubdata_8
   csubdata_8 = new TPad("csubdata_8", "csubdata_8",0.3433333,0.01,0.6566667,0.3233333);
   csubdata_8->Draw();
   csubdata_8->cd();
   csubdata_8->Range(-25,-15.88125,25,142.9313);
   csubdata_8->SetBorderSize(2);
   csubdata_8->SetFrameFillColor(0);
   
   TH1F *Data after pedestals subtraction channel 7__8 = new TH1F("Data after pedestals subtraction channel 7__8","Data after pedestals subtraction channel 7",100,-20,20);
   Data after pedestals subtraction channel 7__8->SetBinContent(7,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(11,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(16,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(17,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(20,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(26,3);
   Data after pedestals subtraction channel 7__8->SetBinContent(27,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(28,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(31,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(33,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(34,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(35,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(36,3);
   Data after pedestals subtraction channel 7__8->SetBinContent(38,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(39,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(40,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(41,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(42,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(43,7);
   Data after pedestals subtraction channel 7__8->SetBinContent(44,8);
   Data after pedestals subtraction channel 7__8->SetBinContent(45,16);
   Data after pedestals subtraction channel 7__8->SetBinContent(46,45);
   Data after pedestals subtraction channel 7__8->SetBinContent(47,44);
   Data after pedestals subtraction channel 7__8->SetBinContent(48,76);
   Data after pedestals subtraction channel 7__8->SetBinContent(49,99);
   Data after pedestals subtraction channel 7__8->SetBinContent(50,118);
   Data after pedestals subtraction channel 7__8->SetBinContent(51,121);
   Data after pedestals subtraction channel 7__8->SetBinContent(52,97);
   Data after pedestals subtraction channel 7__8->SetBinContent(53,105);
   Data after pedestals subtraction channel 7__8->SetBinContent(54,82);
   Data after pedestals subtraction channel 7__8->SetBinContent(55,56);
   Data after pedestals subtraction channel 7__8->SetBinContent(56,31);
   Data after pedestals subtraction channel 7__8->SetBinContent(57,28);
   Data after pedestals subtraction channel 7__8->SetBinContent(58,19);
   Data after pedestals subtraction channel 7__8->SetBinContent(59,5);
   Data after pedestals subtraction channel 7__8->SetBinContent(60,6);
   Data after pedestals subtraction channel 7__8->SetBinContent(61,5);
   Data after pedestals subtraction channel 7__8->SetBinContent(62,3);
   Data after pedestals subtraction channel 7__8->SetBinContent(63,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(64,3);
   Data after pedestals subtraction channel 7__8->SetBinContent(65,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(66,4);
   Data after pedestals subtraction channel 7__8->SetBinContent(69,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(70,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(71,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(72,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(74,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(75,2);
   Data after pedestals subtraction channel 7__8->SetBinContent(77,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(95,1);
   Data after pedestals subtraction channel 7__8->SetBinContent(101,3);
   Data after pedestals subtraction channel 7__8->SetEntries(1024);
   Data after pedestals subtraction channel 7__8->SetDirectory(0);
   
   TF1 *gaus = new TF1("gaus","gaus",-20,20);
   gaus->SetFillColor(19);
   gaus->SetFillStyle(0);
   gaus->SetLineColor(4);
   gaus->SetLineWidth(3);
   gaus->SetChisquare(67.80492);
   gaus->SetNDF(47);
   gaus->SetParameter(0,115.2335);
   gaus->SetParError(0,4.770567);
   gaus->SetParLimits(0,0,0);
   gaus->SetParameter(1,0.2703001);
   gaus->SetParError(1,0.04321835);
   gaus->SetParLimits(1,0,0);
   gaus->SetParameter(2,1.320015);
   gaus->SetParError(2,0.03402909);
   gaus->SetParLimits(2,0,23.74277);
   Data after pedestals subtraction channel 7__8->GetListOfFunctions()->Add(gaus);
   
   ptstats = new TPaveStats(0.6185593,0.631337,0.9774417,0.9301287,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(2);
   ptstats->SetFillColor(19);
   ptstats->SetTextAlign(12);
   text = ptstats->AddText("Data after pedestals subtraction channel 7");
   text->SetTextSize(0.03926977);
   text = ptstats->AddText("Entries = 1024   ");
   text = ptstats->AddText("#chi^{2} / ndf =  67.8 / 47");
   text = ptstats->AddText("Prob  = 0.02507");
   text = ptstats->AddText("Constant = 115.2 #pm 4.8 ");
   text = ptstats->AddText("Mean     = 0.2703 #pm 0.0432 ");
   text = ptstats->AddText("Sigma    =  1.32 #pm 0.03 ");
   ptstats->SetOptStat(11);
   ptstats->SetOptFit(1111);
   ptstats->Draw();
   Data after pedestals subtraction channel 7__8->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Data after pedestals subtraction channel 7__8->GetListOfFunctions());
   Data after pedestals subtraction channel 7__8->GetXaxis()->SetTitle("ADC Counts");
   Data after pedestals subtraction channel 7__8->Draw("");
   
   pt = new TPaveText(0.01,0.9398385,0.71,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(2);
   pt->SetFillColor(19);
   text = pt->AddText("Data after pedestals subtraction channel 7");
   pt->Draw();
   csubdata_8->Modified();
   csubdata->cd();
  
// ------------>Primitives in pad: csubdata_9
   csubdata_9 = new TPad("csubdata_9", "csubdata_9",0.6766667,0.01,0.99,0.3233333);
   csubdata_9->Draw();
   csubdata_9->cd();
   csubdata_9->Range(0,0,1,1);
   csubdata_9->SetBorderSize(2);
   csubdata_9->SetFrameFillColor(0);
   csubdata_9->Modified();
   csubdata->cd();
   csubdata->Modified();
   csubdata->cd();
   csubdata->SetSelected(csubdata);
}
